import type { PropertyType, RentalSource } from "./types";

export const NO = {
  appName: "LEIE",
  tagline: "Bergen-leie",
  filters: "Filtre",
  listings: "annonser",
  cheapest: "Billigst",
  largest: "Størst",
  newest: "Nyest",
  cheapestTotal: "Billigst totalt",
  allTypes: "Alle typer",
  room: "Rom",
  sharedRoom: "Delt rom",
  studio: "Hybel",
  apartment: "Leilighet",
  house: "Hus",
  allSources: "Alle kilder",
  maxMonthly: "Maks månedspris (NOK)",
  noLimit: "Ingen grense",
  includeShortTerm: "Inkluder korttidsleie",
  resetFilters: "Nullstill filtre",
  nokPerMonth: "NOK/mnd",
  bedrooms: "soverom",
  bedroom: "soverom",
  from: "Fra",
  deposit: "depositum",
  noDeposit: "Intet depositum",
  viewOn: "Se på",
  belowMarket: "Under markedspris",
  aroundMarket: "Rundt markedspris",
  aboveMarket: "Over markedspris",
  areaMedian: "Områdemedian",
  below: "under",
  above: "over",
  atMedian: "lik median",
  noMatches: "Ingen treff",
  tryWider: "Prøv å utvide søket ditt",
  reset: "Nullstill",
  propertyType: "Boligtype",
  totalCost: "Estimert totalkostnad/mnd",
  totalCostShort: "Estimert totalt",
  totalCostSortLabel: "Totalt",
  rent: "Husleie",
  electricity: "Estimert strøm",
  internet: "Internett (estimat)",
  transport: "Månedskort (valgfritt)",
  notIncluded: "Ikke inkludert",
  totalCostNote: "Estimert totalt basert på husleie, strøm og typiske månedlige utgifter.",
  confidence: { low: "Lavt grunnlag", medium: "Rimelig estimat", high: "Godt grunnlag" } as const,
  showBreakdown: "Vis detaljer",
  hideBreakdown: "Skjul detaljer",
  assumptions: "Forutsetninger",
  source: "Kilde",
  approximate: "Omtrentlig beliggenhet",
  shortTerm: "Korttid",
  cheapestBadge: "Billigst",
  goodValue: "Godt kjøp",
  underMarketBadge: "Under marked",
  availableNow: "Ledig nå",
  all: "Alle",
  apt: "Leil.",
  marketPriceSignal: "Markedsprisindikator"
};

export const propertyTypeLabelsNo: Record<PropertyType, string> = {
  house: NO.house,
  apartment: NO.apartment,
  room: NO.room,
  shared_room: NO.sharedRoom,
  studio: NO.studio,
  unknown: "Ukjent"
};

export const sourceLabelsNo: Record<RentalSource, string> = {
  finn: "FINN.no",
  airbnb: "Airbnb",
  hybel: "Hybel.no",
  utleiemegleren: "Utleiemegleren",
  heimstaden: "Heimstaden",
  mock: "Mock"
};
